### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by lonbar**
I've rewritten the README; it should list all the features we currently support.

### CODE REVIEW

**Comment by lonbar** [comment]
We probably want to add animations to this, to illustrate the functionality. @nikosarcevic can you split up the video you made into separate pieces? In that case we can add the videos to the relevant sections.

**Comment by nikosarcevic** [comment]
> We probably want to add animations to this, to illustrate the functionality. @nikosarcevic can you split up the video you made into separate pieces? In that case we can add the videos to the relevant sections.

Ja I can make a new video

**Comment by lonbar** [comment]
(can you also review this pull request?)

**Review by nikosarcevic — CHANGES_REQUESTED** [review]
looking good. ty, matthijs
I would add one thing - just before line 14 I would just first say Cosmoracle is a web app that for now calculates distances In cosmology (or something like that so it leaves a suggestion we will expand more and add more features)


secondly, can we mention somewhere the app is accessible and works well on dessktop, tablet and mobile?

**Pull request merged**
