### PR TITLE
introduced data class for parameter handling.

### PR DESCRIPTION
**Pull request by lonbar**

### CODE REVIEW

**Comment by marcobonici** [comment]
Hi @lonbar , thenak you for the PR.

The code you have written is right (I didn't find any bug), however there are a couple of points I'd like to discuss with you beofre merging.

1. The `dataclass` is defined inside the distance page. I would avoid this because, if we are gonna use the same class in more pages, we should define them in a different module (as we did for `background.py`) to be imported later; plus, I consider that is better to keep separate the files which are related to our "cosmological tools" and the ones about Streamlit.
2. I would consider defining the functions in `background.py` as method of the class you have defined. It looks a bit confusing to me (and possibly buggy) to define `distanceParamas` methods referencing to external methods. 
3. Why did you use `dataclass` ? This is not an argument against this, I have never used this class so I was wondering which are the main benefits of this choice.

**Comment by lonbar** [comment]
Those are good points.
1. Agreed. I'll create a separate file for the class.
2. I'm not sure I understand exactly what you mean. Currently, the functions of `backgrounds.py` are used to construct the internal functions of the data class. My reasoning for adding them is that you do not have to repeatedly specify all the different parameters. Instead, a given set of parameters is handled only once, and the implementation can be checked in a single location. (the naming could be optimised though, the current naming is only tentative.)
3. I used `dataclass` because that was Wessel's suggestion. Did I miss something here?

**Comment by marcobonici** [comment]
1. Ock!
2. For instance, you defined
```
def comovingDistance(self) -> float:
    return bg.comoving_distance(self.redshift, self.H0, self.ΩM, self.ΩDE, 
                                self.ΩR, self.w0, self.wa)
```
   while I would have embedded the previous methods in your class

```
def E_z(self, z):
    """
    Method to compute the adimensional Hubble rate in the w0waCDm cosmology
    """
    if isinstance(z, float) or isinstance(z, int):
        if z < 0:
            raise TypeError("Enter a non-negative redshift.")
    elif isinstance(z, np.ndarray):
        if any(t < 0 for t in z):
            raise TypeError("Enter a non-negative redshift.")
    ΩK = 1-self.ΩM-self.ΩDE-self.ΩR
    return np.sqrt(self.ΩM*(1+z)**3+self.ΩR*(1+z)**4+self.ΩDE*(1+z)**(3*(1+self.w0+self.wa))*np.exp(-3*self.wa*z/(1+z))+ΩK*(1+z)**2)
```

```
def comoving_distance(self, z):
    """
    Method to compute the comoving distance
    """
    integrand = lambda x: 1/self.E_z(x)
    if isinstance(z, float) or isinstance(z, int):
        if z < 0:
            raise TypeError("Enter a non-negative redshift.")
        result, _ = integrate.quad(integrand, 0, z)
    elif isinstance(z, np.ndarray):
        if any(t < 0 for t in z):
            raise TypeError("Enter a non-negative redshift.")
        result = np.vectorize(lambda x: integrate.quad(integrand, 0, x)[0])(z)
    else:
        raise TypeError(f'Expected "Union[float, np.ndarray]", got {type(z)}')
    c0 = constants['speed-of-light']
    return c0/H0*result
```
3. Fine with it!:)

**Comment by lonbar** [comment]
Ah, I see. So you want to replace the separate functions from `backgrounds.py` with the data class completely?

**Comment by marcobonici** [comment]
I would move all functions from `background.py` to the class you have defined.

**Comment by marcobonici** [comment]
Of course I don't want to decide this by myself alone.
So, if you have a different opinion this is not a problem and we can discusse about it @nikosarcevic @lonbar :smile:

**Comment by lonbar** [comment]
I've started to implement what @marcobonici suggested, but the more I read the less sure I was whether that is the right way to go about.

If I understand the dataclass correctly, then we should mostly use it for storing data, and try not to embed too many functions in it. I have at least two reasons for this:
1. The function definitions will get more verbose, as each variable must be prefixed by `self.` (e.g. self.H0). This creates more dense text that is *less* easy to maintain.
2. Embedding structures limits their scope. If we embed `E_z` in the dataclass, then it will only be accessible to that particular data class. Should we later need `E_z` for something else (a separate computation behind the screen, or a separate dataset), then we'd have to reimplement that function.

I suggest the following:
1. Rename the functions in `background.py` by prefixing them with something like `get_` or `compute_` (e.g. `get_comoving_distance). This should hopefully clear up any confusion on what function is being called.
2. Implement a data class that handles all the quantities (parameters _or_ distance measures) along the lines of
````
@dataclass
class distanceData:
    par1: float
    par2: float = constants['par2']
    measure1: float = field(init=False)

    def __post_init__(self):
        measure1  = get_measure1(self.par1, self.par2)
````
So when distanceData is called, only `par1` and `par2` are put in by the user (`par2` has a default value from `constants.yaml`). `measure` is determined by `distanceData` using the function `get_measure1`. I am not sure if it makes more sens to put this class in a separate file or in `background.py` itself. @marcobonici seems to suggest the latter? @nikosarcevic what do you think? Or maybe we should have a quick chat about this tomorrow?

In any case, I think that the simplest thing would be to discard this pull request and start from fresh; we wouldn't have to undo the commits of this branch, and by now this pull request is blocking others.

**Comment by marcobonici** [comment]
Fine with me. Probably a chat will help us understanding which is the best choice:)

**Pull request merged**
